# Generated by Django 3.0.4 on 2020-03-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Img',
            field=models.ImageField(null=True, upload_to='images/users', verbose_name='image'),
        ),
    ]
