# Generated by Django 3.0.4 on 2020-03-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200321_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/Users'),
        ),
    ]
