# Generated by Django 3.0.4 on 2020-03-17 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_projects',
            name='featured_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
