# Generated by Django 3.0.4 on 2020-03-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='user_id',
            new_name='user',
        ),
    ]
