# Generated by Django 3.0.4 on 2020-03-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/projects', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
