# Generated by Django 3.0.4 on 2020-03-17 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200317_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_projects',
            name='featured_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
