# Generated by Django 3.0.4 on 2020-08-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200813_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='featured_date',
            field=models.DateTimeField(),
        ),
    ]
