# Generated by Django 3.0.4 on 2020-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20200317_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='report',
            field=models.IntegerField(null=True),
        ),
    ]
