# Generated by Django 3.0.4 on 2020-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20200326_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='report',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
