# Generated by Django 3.0.4 on 2020-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20200318_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
