# Generated by Django 3.0.4 on 2020-03-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Projects', '0005_auto_20200320_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='Path',
        ),
        migrations.AddField(
            model_name='pictures',
            name='image',
            field=models.ImageField(null=True, upload_to='images/projects', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Users'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images_project', to='Projects.Projects'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
