# Generated by Django 3.0.4 on 2020-03-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20200319_1425'),
        ('Projects', '0005_auto_20200320_1125'),
    ]

    operations = [
    ]
