# Generated by Django 3.0.4 on 2020-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Projects', '0007_auto_20200321_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='project_Id',
        ),
        migrations.AlterField(
            model_name='projects',
            name='donations',
            field=models.ManyToManyField(null=True, related_name='UserDonations', through='Projects.user_donations', to='Users.Users'),
        ),
    ]
