# Generated by Django 3.0.4 on 2020-03-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20200321_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='category',
            new_name='category_id',
        ),
    ]
