# Generated by Django 3.0.4 on 2020-03-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20200321_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='category_id',
            new_name='category',
        ),
    ]
